---
sources:
  go: true
allowed:
  - mit
  - apache-2.0
  - mpl-2.0
  - bsd-2-clause
  - bsd-3-clause
  - isc
reviewed:
  go:
    - github.com/magiconair/properties # bsd-2-clause
    - gopkg.in/ini.v1 # apache-2.0
    - gopkg.in/yaml.v2 # apache-2.0
    - golang.org/x/**/* # bsd-style
